name: Exercise_9_build_test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  BUILD:
    name: Build_&_Run_job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_step
        uses: actions/checkout@v2.3.4
      - name: Install_step
        run: sudo apt-get install build-essential
      - name: Build_step
        run: make
      - name: Test_step
        run: make check_stack
          make check_expr
      - name: Run_step
        run: make STR="2*(3-(4+2))-((1-6)/3)" run
